### ISSUE TITLE
install question

### ISSUE THREAD

**Issue by zyd6** [suecodelabs/cnfuzz#120]
helm install cnfuzz cnfuzz/cnfuzz    
  

return an error :Error: INSTALLATION FAILED: failed post-install: timed out waiting for the condition

iwant to know :need whose condition

**Comment by pcktdmp** [comment]
Hi @zyd6!

Thanks for you inquiry! 
We are currently looking into the issue.

Have you already tried to use cnfuzz from the [latest](https://github.com/suecodelabs/cnfuzz/releases/tag/v0.2.0) release tag?

**Comment by zyd6** [comment]
I used the way
1、helm repo add cnfuzz https://suecodelabs.github.io/cnfuzz
2、helm repo update
3 、helm install cnfuzz cnfuzz/cnfuzz
The third step of the installation timed out. Do you have any preconditions

**Comment by Luukvdm** [comment]
The default helm values start a Minio and a Redis instance that can take awhile to start.
You could probably figure out if those are the problem by looking at the events inside your cluster.

Also, we still use the default namespace in our helm chart (we should probably change that 😅), if you want to deploy in a different namespace you can use `helm install cnfuzz cnfuzz/cnfuzz --namespace mynamespace`

**Comment by zyd6** [comment]
hi 
this is pod's error when run this step   :    helm install cnfuzz cnfuzz/cnfuzz
 Warning  FailedScheduling  21s (x12 over 15m)  default-scheduler  running "VolumeBinding" filter plugin for pod "cnfuzz-redis-master-0": pod has unbound immediate PersistentVolumeClaims


can you give me help ?

**Comment by zyd6** [comment]
Do I need to prepare PVC with a specific name in the namespace

**Comment by zyd6** [comment]
<img width="794" alt="企业微信截图_16685018911255" src="https://user-images.githubusercontent.com/37687944/201872230-a1fbefd5-fc56-4661-a4b2-8d9f78cdcc14.png">

**Comment by zyd6** [comment]
yes
<img width="634" alt="企业微信截图_16685020735747" src="https://user-images.githubusercontent.com/37687944/201872944-ac021ba7-a686-4088-8c5b-190668a5cf54.png">

**Comment by zyd6** [comment]
<img width="634" alt="企业微信截图_1668502124834" src="https://user-images.githubusercontent.com/37687944/201873135-df2b0ec3-032a-4119-b620-d51425c5a045.png">

**Comment by zyd6** [comment]
Hello

I deleted pvc and reinstalled cnfuzzy, but this problem still exists



running "VolumeBinding" filter plugin for pod "cnfuzz-minio-784497456b-f6kbx": pod has unbound immediate PersistentVolumeClaims

**Comment by Luukvdm** [comment]
In your screenshots it looks like the default storage class for minio and redis don't work for your cluster. If you would want to set them manually you would do something like this:

`helm install cnfuzz cnfuzz/cnfuzz --set minio.persistence.storageClass=statefu-nfs,redis.global.storageClass=statefu-nfs`

If you need more info about those charts, you can find them here:
https://github.com/bitnami/charts/tree/main/bitnami/redis
https://github.com/minio/minio/tree/master/helm/minio

Let me know if that solves the issue.

**Comment by zyd6** [comment]
so Great This problem has been solved!!!

**Comment by zyd6** [comment]
<img width="375" alt="企业微信截图_16685047285639" src="https://user-images.githubusercontent.com/37687944/201883446-fbdd0a94-5f7a-40e6-aa82-a31ddbb85b11.png">

**Comment by zyd6** [comment]
<img width="305" alt="企业微信截图_16685047754187" src="https://user-images.githubusercontent.com/37687944/201883617-2c6301e7-63c6-4150-bcb6-9987127bff85.png">

**Comment by pcktdmp** [comment]
Great that it works now @zyd6!
